# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'U17' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Moya/Core'

  # Pods for U17

  target 'U17Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'U17UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
